apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nativeBuildConfig
  labels:
    quarkus-buildtype: 'native'
spec:
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: https://github.com/pittar-sandbox/quarkus-native-test.git
      ref: main
    dockerfile: |-
      FROM registry.access.redhat.com/quarkus/mandrel-for-jdk-21-rhel8:23.1 AS builder
      USER root
      WORKDIR /build/
      COPY . /build/
      RUN ./mvnw clean package -Pnative
      
      FROM registry.redhat.io/ubi8/ubi-minimal
      WORKDIR /deployments/
      COPY --from=builder /build/target/*-runner /deployments/application
      RUN chmod 110 /deployments/application
      CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
  output:
    to:
      kind: ImageStream
      name: testApp:latest
  triggers:
    - type: ConfigChange
