apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: quarkus-native
  labels:
    quarkus-buildtype: 'native'
spec:
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: https://github.com/pittar-sandbox/quarkus-native-test.git
      ref: main
    contextDir: .
  output:
    to:
      kind: ImageStream
      name: "testapp"
  triggers:
    - type: ConfigChange
